# Exercício de Programação 5: 4 formas de resolver mínimos quadrados

<font color="red">**Prazo de submissão: 23:55 do dia 14/02/2022** </font>

2021.2 Álgebra Linear Computacional - DCC - UFMG

Erickson - Fabricio

Instruções:
* Antes de submeter suas soluções, certifique-se de que tudo roda como esperado. Primeiro, **reinicie o kernel** no menu, selecione Kernel $\rightarrow$ Restart e então execute **todas as células** (no menu, Cell $\rightarrow$ Run All)
* **Transfira suas respostas para o arquivo .py com atenção.**
* **Confira se a indentação está correta antes de submeter.**
* Apenas o arquivo .py deve ser submetido. Ele não deve ser compactado.

## Carregando os dados

Iremos carregar os dados usando a biblioteca ```pandas```. Não se preocupe se você não conhece a biblioteca, pois o nosso objetivo é apenas extrair a matriz de dados $X$. Segue uma descrição do dataset, retirada [daqui](http://statweb.stanford.edu/~owen/courses/202/Cereals.txt).

* Datafile Name: Cereals
* Datafile Subjects: Food , Health
* Story Names: Healthy Breakfast
* Reference: Data available at many grocery stores
* Authorization: free use
* Description: Data on several variable of different brands of cereal.

A value of -1 for nutrients indicates a missing observation.
Number of cases: 77
Variable Names:

  1. Name: Name of cereal
  2. mfr: Manufacturer of cereal where A = American Home Food Products; G =
     General Mills; K = Kelloggs; N = Nabisco; P = Post; Q = Quaker Oats; R
     = Ralston Purina
  3. type: cold or hot
  4. calories: calories per serving
  5. protein: grams of protein
  6. fat: grams of fat
  7. sodium: milligrams of sodium
  8. fiber: grams of dietary fiber
  9. carbo: grams of complex carbohydrates
  10. sugars: grams of sugars
  11. potass: milligrams of potassium
  12. vitamins: vitamins and minerals - 0, 25, or 100, indicating the typical percentage of FDA recommended
  13. shelf: display shelf (1, 2, or 3, counting from the floor)
  14. weight: weight in ounces of one serving
  15. cups: number of cups in one serving
  16. rating: a rating of the cereals

In [1]:
#Execute esta célula para instalar o pandas caso já não tenha instalado
# import sys
# !{sys.executable} -m pip install --user pandas

In [2]:
import pandas as pd
df = pd.read_table('cereal.txt',sep='\s+',index_col='name')
df

mfr type  calories  protein  fat  sodium  fiber  \
name                                                                        
100%_Bran                   N    C        70        4    1     130   10.0   
100%_Natural_Bran           Q    C       120        3    5      15    2.0   
All-Bran                    K    C        70        4    1     260    9.0   
All-Bran_with_Extra_Fiber   K    C        50        4    0     140   14.0   
Almond_Delight              R    C       110        2    2     200    1.0   
...                        ..  ...       ...      ...  ...     ...    ...   
Triples                     G    C       110        2    1     250    0.0   
Trix                        G    C       110        1    1     140    0.0   
Wheat_Chex                  R    C       100        3    1     230    3.0   
Wheaties                    G    C       100        3    1     200    3.0   
Wheaties_Honey_Gold         G    C       110        2    1     200    1.0   

                           carbo  sugars  potass  vitamins  shelf  weight  \
name                                                                        
100%_Bran                    5.0       6     280        25      3     1.0   
100%_Natural_Bran            8.0       8     135         0      3     1.0   
All-Bran                     7.0       5     320        25      3     1.0   
All-Bran_with_Extra_Fiber    8.0       0     330        25      3     1.0   
Almond_Delight              14.0       8      -1        25      3     1.0   
...                          ...     ...     ...       ...    ...     ...   
Triples                     21.0       3      60        25      3     1.0   
Trix                        13.0      12      25        25      2     1.0   
Wheat_Chex                  17.0       3     115        25      1     1.0   
Wheaties                    17.0       3     110        25      1     1.0   
Wheaties_Honey_Gold         16.0       8      60        25      1     1.0   

                           cups     rating  
name                                        
100%_Bran                  0.33  68.402973  
100%_Natural_Bran          1.00  33.983679  
All-Bran                   0.33  59.425505  
All-Bran_with_Extra_Fiber  0.50  93.704912  
Almond_Delight             0.75  34.384843  
...                         ...        ...  
Triples                    0.75  39.106174  
Trix                       1.00  27.753301  
Wheat_Chex                 0.67  49.787445  
Wheaties                   1.00  51.592193  
Wheaties_Honey_Gold        0.75  36.187559  

[77 rows x 15 columns]

A seguir iremos remover as linhas correspondentes aos cereais que possuem dados faltantes, representados pelo valor -1.
Também iremos remover as colunas com dados categóricos 'mfr' e 'type', e os dados numéricos, 'shelf', 'weight' e 'cups'.

In [3]:
import numpy as np
new_df = df.replace(-1,np.nan)
new_df = new_df.dropna()
new_df = new_df.drop(['mfr','type','shelf','weight','cups'],axis=1)
new_df

calories  protein  fat  sodium  fiber  carbo  \
name                                                                      
100%_Bran                        70        4    1     130   10.0    5.0   
100%_Natural_Bran               120        3    5      15    2.0    8.0   
All-Bran                         70        4    1     260    9.0    7.0   
All-Bran_with_Extra_Fiber        50        4    0     140   14.0    8.0   
Apple_Cinnamon_Cheerios         110        2    2     180    1.5   10.5   
...                             ...      ...  ...     ...    ...    ...   
Triples                         110        2    1     250    0.0   21.0   
Trix                            110        1    1     140    0.0   13.0   
Wheat_Chex                      100        3    1     230    3.0   17.0   
Wheaties                        100        3    1     200    3.0   17.0   
Wheaties_Honey_Gold             110        2    1     200    1.0   16.0   

                           sugars  potass  vitamins     rating  
name                                                            
100%_Bran                     6.0   280.0        25  68.402973  
100%_Natural_Bran             8.0   135.0         0  33.983679  
All-Bran                      5.0   320.0        25  59.425505  
All-Bran_with_Extra_Fiber     0.0   330.0        25  93.704912  
Apple_Cinnamon_Cheerios      10.0    70.0        25  29.509541  
...                           ...     ...       ...        ...  
Triples                       3.0    60.0        25  39.106174  
Trix                         12.0    25.0        25  27.753301  
Wheat_Chex                    3.0   115.0        25  49.787445  
Wheaties                      3.0   110.0        25  51.592193  
Wheaties_Honey_Gold           8.0    60.0        25  36.187559  

[74 rows x 10 columns]

Finalmente, iremos converter os dados nutricionais numéricos de ```new_df``` para uma matriz X ('calories', 'protein', 'fat', 'sugars' e 'vitamins') e as avaliações (ratings) para um vetor $y$. Os nomes dos cereais serão salvos em uma lista ```cereral_names``` e os nomes das colunas em uma lista ```col_names```.

In [4]:
cereral_names = list(new_df.index)
print('Cereais:',cereral_names)
col_names = list(new_df.columns)
print('Colunas:',col_names)

X = new_df.loc[:,['calories', 'protein', 'fat', 'sugars', 'vitamins']].values
print('As dimensões de dados são:',X.shape)
y = new_df['rating'].values
print('As dimensões de y são:',y.shape)


Cereais: ['100%_Bran', '100%_Natural_Bran', 'All-Bran', 'All-Bran_with_Extra_Fiber', 'Apple_Cinnamon_Cheerios', 'Apple_Jacks', 'Basic_4', 'Bran_Chex', 'Bran_Flakes', "Cap'n'Crunch", 'Cheerios', 'Cinnamon_Toast_Crunch', 'Clusters', 'Cocoa_Puffs', 'Corn_Chex', 'Corn_Flakes', 'Corn_Pops', 'Count_Chocula', "Cracklin'_Oat_Bran", 'Crispix', 'Crispy_Wheat_&_Raisins', 'Double_Chex', 'Froot_Loops', 'Frosted_Flakes', 'Frosted_Mini-Wheats', 'Fruit_&_Fibre_Dates,_Walnuts,_and_Oats', 'Fruitful_Bran', 'Fruity_Pebbles', 'Golden_Crisp', 'Golden_Grahams', 'Grape_Nuts_Flakes', 'Grape-Nuts', 'Great_Grains_Pecan', 'Honey_Graham_Ohs', 'Honey_Nut_Cheerios', 'Honey-comb', 'Just_Right_Crunchy__Nuggets', 'Just_Right_Fruit_&_Nut', 'Kix', 'Life', 'Lucky_Charms', 'Maypo', 'Muesli_Raisins,_Dates,_&_Almonds', 'Muesli_Raisins,_Peaches,_&_Pecans', 'Mueslix_Crispy_Blend', 'Multi-Grain_Cheerios', 'Nut&Honey_Crunch', 'Nutri-Grain_Almond-Raisin', 'Nutri-grain_Wheat', 'Oatmeal_Raisin_Crisp', 'Post_Nat._Raisin_Bran', 'Prod

## Sistemas Lineares e Mínimos Quadrados

Esse Exercício de Programação irá tratar das 4 formas de resolver a otimização de mínimos quadrados a partir da equação normal, iremos estimar os parâmetros de um regressor linear para o nosso dataset de cereais.

Dado o sistema linear $X\beta = b$, procuramos encontrar o valor de de $\hat{\beta}$ que minimiza o erro quadrático $||X\hat{\beta}-b||^{2}$.

Esse valor é definido pela **Equação Normal**:

$X^{T}X\hat{\beta} = X^{T}b$.

Foram apresentados em aula quatro métodos para resolver a Equação Normal:
- Inversa da matriz $X^{T}X$
- Pseudo-Inversa
- Decomposição QR
- Decomposição de Cholesky

Para relembrar os conceitos, revise as aulas [19](https://www.youtube.com/watch?v=SBsdyq2ha5k) e [20](https://www.youtube.com/watch?v=wuTbS0FOkLY).

**ATENÇÃO:**
- Programe as questões abaixo com atenção para as funções da biblioteca numpy que são permitidas. 
- Não serão aceitos trabalhos em que a questão foi resolvida utilizando funções não permitidas. 
- Para todas as questões, as operações básicas de multiplicação de matrizes serão permitidas.

In [5]:
## Não altere essa célula
import numpy as np

**1.1** Inversa da matriz $X^{T}X$

Defina a função **inversa(X, y)** (*1.1.1*) para calcular os parâmetros $\hat{\beta}$ a partir do método de **inversão da matriz $X^{T}X$**.

**Funções permitidas:**

[np.linalg.inv](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html)

In [6]:
def inversa(X, y):
    XTX = X.T @ X
    XTX_inv = np.linalg.inv(XTX)
    
    return XTX_inv @ (X.T @ y)

print(inversa(X, y))

[ 0.38007547  9.26234589 -7.97694968 -1.56898833 -0.14023927]


**1.2** Pseudo-inversa

Defina a função **pseudo_inversa(X, y)** (*1.2.1*) para calcular os parâmetros $\hat{\beta}$ a partir do método da **pseudo-inversa**.

**Funções permitidas:**

[np.linalg.svd](https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html)

In [7]:
def pseudo_inversa(X, y):
    U, Sigma, Vt = np.linalg.svd(X, full_matrices=False)
        
    pseudo_inv = Vt.T @ np.diag((1 / Sigma)) @ U.T
    
    return pseudo_inv @ y

print(pseudo_inversa(X, y))

[ 0.38007547  9.26234589 -7.97694968 -1.56898833 -0.14023927]


**1.3** Decomposição QR

Defina a função **QR(X, y)** (*1.3.1*) para calcular os parâmetros $\hat{\beta}$ a partir do método de **Decomposição QR**.

**Funções permitidas:**

[np.linalg.inv](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html)

[np.linalg.qr](https://numpy.org/doc/stable/reference/generated/numpy.linalg.qr.html)

In [8]:
def QR(X, y):
    Q, R = np.linalg.qr(X)
    
    return np.linalg.inv(R) @ Q.T @ y
    
print(QR(X, y))

[ 0.38007547  9.26234589 -7.97694968 -1.56898833 -0.14023927]


**1.4** Decomposição de Cholesky

Defina as funções **substituicao(L, b)** (*1.4.1*) e **retrosubstituicao(Lt, C)** (*1.4.2*) como funções auxiliares para efetuar as substituições do método pela **Decomposição de Cholesky**. Crie também as funções **positiva_definida(X)** (*1.4.3*) e **simetrica(X)** (*1.4.4*) que retornam um *booleano* indicando se a matriz de entrada é positiva definida e simétrica, respectivamente.

A partir das funções definidas anteriormente, crie uma função chamada **cholesky(X, y)** (*1.4.5*) para calcular os parâmetros $\hat{\beta}$ a partir do método de **Decomposição de Cholesky**, utilize a função **assert** do python e as funções **positiva_definida(X)** e **simetrica(X)** para garantir que a matriz decomposta é simétrica definida positiva.

**Funções permitidas:**

[np.linalg.cholesky](https://numpy.org/doc/stable/reference/generated/numpy.linalg.cholesky.html)

[np.linalg.eigvals](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigvals.html)

[np.allclose](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html)

[np.all](https://numpy.org/doc/stable/reference/generated/numpy.all.html)


In [10]:
def substituicao(L, b):
    return np.linalg.inv(L) @ b
    
def retrosubstituicao(Lt, C):
    return np.linalg.inv(Lt) @ C
    
def positiva_definida(X):
    return np.all(np.linalg.eigvals(X) > 0)
    
def simetrica(X):
    return np.allclose(X, X.T)
    
def cholesky(X, y):
    assert positiva_definida(X.T @ X), 'A matriz de entrada não é positiva definida'
    assert simetrica(X.T @ X), 'A matriz de entrada não é simétrica'
    
    L = np.linalg.cholesky(X.T @ X)
    C = substituicao(L, X.T @ y)
    
    return retrosubstituicao(L.T, C)
    
print(cholesky(X, y))

[ 0.38007547  9.26234589 -7.97694968 -1.56898833 -0.14023927]


Vamos visualizar os parâmetros estimados utilizando cada método:

In [ ]:
## Insira seu código aqui e descomente o código para imprimir os resultados

#betas_pseudo_inversa = 
#betas_inversa = 
#betas_qr = 
#betas_cholesky = 

#print(betas_pseudo_inversa)
#print(betas_inversa)
#print(betas_qr)
#print(betas_cholesky)